swagger: '2.0'
info:
  version: 2.1.0
  title: HealthTap Cloud
  description: >-
    HealthTap cloud is a open platform where top health developers make their
    apps interoperable, engaging, and smart
  termsOfService: 'https://www.healthtap.com/terms'
  contact:
    name: HealthTap API Team
  license:
    name: MIT
securityDefinitions:
  oauth:
    type: oauth2
    authorizationUrl: 'https://next-enterpriseqa.healthtap.com/oauth/authorize'
    tokenUrl: 'https://next-enterpriseqa.healthtap.com/oauth/token'
    flow: accessCode
    scopes:
      member_write: modify your account
      member_read: read your profile
host: next-enterpriseqa.healthtap.com
basePath: /api/v2.1
paths:
  /users/me/basic_profile:
    get:
      description: Get current user's basic profile
      operationId: User Profile
      summary: Get Basic Profile
      tags:
        - User
      security:
        - oauth:
            - member_read
    put:
      description: >-
        Update health profiles for current user. You can update the following
        fields with value and unit:
              city, state, country, postcode, gender, dob, given_name, family_name, middle_name, email, phone, phone_country_code,
              address_line_1, address_line_2, address_city, address_state, address_postcode, address_country.
              If you want to customize fields, please contact us.
      operationId: put_health_profile
      summary: Update Basic Profile
      tags:
        - User
      security:
        - oauth:
            - member_write
  /users/me/feed:
    get:
      description: Get user's feed
      operationId: User feed
      summary: Get Feed
      tags:
        - Engagement
      security:
        - oauth:
            - member_read
  /users/me/checklists:
    get:
      description: Get user's checklists
      operationId: User checklists
      summary: Get Checklists
      tags:
        - Engagement
      security:
        - oauth:
            - member_read
  /users:
    post:
      description: Create a new user account
      operationId: Create User Account
      summary: Create User Account
      tags:
        - User
      security:
        - {}
  /users/me/health_profile:
    put:
      description: >-
        Update health profiles for current user. You can update the following
        fields with value and unit:
              city, state, country, postcode, gender, dob, given_name, family_name, middle_name, email, phone, phone_country_code,
              address_line_1, address_line_2, address_city, address_state, address_postcode, address_country,
              ethnicity, height, weight, dietary_restriction, sexually_active, alcohol_use,
              tobacco_use, recreational_drug_use.
              If you want to customize fields, please contact us.
      operationId: put_health_profile
      summary: Update Health Profile
      tags:
        - User
      security:
        - oauth:
            - member_write
    get:
      description: |-
        <p>Get current user's overall health profile</p>

              <div class='profile-item profile-title-wrap'><div class='profile-property profile-title'>Property</div><div class='profile-description profile-title'>Description</div></div>

              <div class='profile-item'><div class='profile-property'>Medications</div><div class='profile-description'>A list of medications, including notes, that user either took in the past or is currently taking</div></div>

              <div class='profile-item'><div class='profile-property'>Allergies</div><div class='profile-description'>A list of medical allergies the user has experienced so far</div></div>

              <div class='profile-item'><div class='profile-property'>Conditions and Symptoms</div><div class='profile-description'>A list of conditions and symptoms the user has exhibited so far</div></div>

              <div class='profile-item'><div class='profile-property'>Treatments</div><div class='profile-description'>A list of treatments, including notes, the user has undergone so far</div></div>

              <div class='profile-item'><div class='profile-property'>Vaccinations</div><div class='profile-description'>A list of vaccinations the user has been given so far</div></div>

              <div class='profile-item'><div class='profile-property'>Pregnancy</div><div class='profile-description'>The user's pregnancy details</div></div>

              <div class='profile-item'><div class='profile-property'>Family History</div><div class='profile-description'>Health profiles of the user's family members</div></div>

              <div class='profile-item'><div class='profile-property'>Pharmacy Details</div><div class='profile-description'>The address and ID of the pharmacy the user use to fill medications</div></div>

              <div class='profile-item'><div class='profile-property'>Lifestyle</div><div class='profile-description'>The user's dietary_restrictions, recreational_drug use, alcohol use, tobacco use and sexual activity</div></div>

              <div class='profile-item'><div class='profile-property'>Health Metrics</div><div class='profile-description'>The user's health metrics</div></div>

              <div class='profile-item'><div class='profile-property'>Lab results</div><div class='profile-description'>A list of the user's test results</div></div>

              <div class='profile-item'><div class='profile-property'>Mailing Address</div><div class='profile-description'>The user's mailing address</div></div>

              <div class='profile-item'><div class='profile-property'>Mobile phone</div><div class='profile-description'>The user's mobile phone</div></div>

              <div class='profile-item'><div class='profile-property'>Work Email</div><div class='profile-description'>The user's work email</div></div>

              <div class='profile-item'><div class='profile-property'>Photo</div><div class='profile-description'>The user's photo url</div></div>

              <div class='profile-item'><div class='profile-property'>Age</div><div class='profile-description'>The user's age</div></div>

              <div class='profile-item'><div class='profile-property'>Gender</div><div class='profile-description'>The user's gender</div></div>

              <div class='profile-item'><div class='profile-property'>Ethnicity</div><div class='profile-description'>The user's ethnicity</div></div>

              <div class='profile-item'><div class='profile-property'>Height</div><div class='profile-description'>The user's height</div></div>

              <div class='profile-item'><div class='profile-property'>Weight</div><div class='profile-description'>The user's weight</div></div>
              
      operationId: get_health_profiles
      summary: Get Health Profile
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/ccds:
    get:
      description: Return full CCDs available for the user including the raw xml.
      operationId: get_CCD
      summary: Get CCD
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/timeline:
    get:
      description: |-
        <p>Get a list of medical timeline of the user</p>

              <div class='profile-item profile-title-wrap'><div class='profile-property profile-title'>Timeline Types</div><div class='profile-description profile-title'>Details</div></div>

              <div class='profile-item'><div class='profile-property'>Asked a question</div><div class='profile-description'>question: question text,<br>question_id: question id</div></div>

              <div class='profile-item'><div class='profile-property'>Completed a consult</div><div class='profile-description'>consult_reason: the reason to call for a consult,<br>expert: expert you did consult with</div></div>

              <div class='profile-item'><div class='profile-property'>Added a health metrics</div><div class='profile-description'>category: category of added health metrics,<br>value: value of the metrics, <br>unit: the unit of the metrics</div></div>

              <div class='profile-item'><div class='profile-property'>Scheduled an appointment</div><div class='profile-description'>appointment_id: appointment id,<br>expert: expert you will talked to, <br> appointment_time: appointment time, <br> appointment reason: the reason for this appointment</div></div>

              <div class='profile-item'><div class='profile-property'>Made a test order</div><div class='profile-description'>type: type of test,<br>test_order_id: test order id</div></div>

              <div class='profile-item'><div class='profile-property'>Received a test result</div><div class='profile-description'>type: type of test,<br>test_order_id: test order id, <br>result: the result of test</div></div>

              <div class='profile-item'><div class='profile-property'>Received a prescription</div><div class='profile-description'>prescription_id: prescription id,<br>prescription: prescription details</div></div>

              <div class='profile-item'><div class='profile-property'>Added a topic</div><div class='profile-description'>topic_id: topic id,<br>topic_type: topic type, <br>topic_name: the name of topic</div></div>

              
      operationId: get_timeline
      summary: Get Timeline
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/health_metrics:
    get:
      description: |-
        <p>Get current user health metrics</p>

              <div class='profile-item profile-title-wrap'><div class='profile-property profile-title'>Property</div><div class='profile-description profile-title'>Unit / Value type</div></div>

              <div class='profile-item'><div class='profile-property'>Body Fat Percentage</div><div class='profile-description'>percentage / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Body Mass Index</div><div class='profile-description'>BMI / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Height</div><div class='profile-description'> ft / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Lean Body Mass</div><div class='profile-description'> lbs / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Weight</div><div class='profile-description'> lbs / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Active Calories</div><div class='profile-description'> cal / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Cyclling Distance</div><div class='profile-description'> miles / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Steps</div><div class='profile-description'> Steps / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Running Walking Distance</div><div class='profile-description'> miles / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Type</div><div class='profile-description'> type / String</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Glucose</div><div class='profile-description'> mg/dl / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Inhaler Usage</div><div class='profile-description'> times / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Oxygen Saturation</div><div class='profile-description'> percentage / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Peak Expiratory Flow Rate</div><div class='profile-description'> l/min / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Body Temperature</div><div class='profile-description'> celsius / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Pressure Diastolic</div><div class='profile-description'> mmhg / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Pressure Systolic</div><div class='profile-description'> mmhg / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Heart Rate</div><div class='profile-description'> beats/minute / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Respiratory Rate</div><div class='profile-description'> breaths/minute / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Dietary Calories</div><div class='profile-description'> cal / Integer</div></div>

              
      operationId: get_health_metrics
      summary: Get Health Metrics
      tags:
        - User
      security:
        - oauth:
            - member_read
    post:
      description: >-
        Update user health metrics, with the following property, value type and
        unit.
              <div class='profile-item profile-title-wrap'><div class='profile-property profile-title'>Property</div><div class='profile-description profile-title'>Unit / Value type</div></div>

              <div class='profile-item'><div class='profile-property'>Body Fat Percentage</div><div class='profile-description'>percentage / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Body Mass Index</div><div class='profile-description'>BMI / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Height</div><div class='profile-description'> ft / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Lean Body Mass</div><div class='profile-description'> lbs / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Weight</div><div class='profile-description'> lbs / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Active Calories</div><div class='profile-description'> cal / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Cyclling Distance</div><div class='profile-description'> miles / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Steps</div><div class='profile-description'> Steps / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Running Walking Distance</div><div class='profile-description'> miles / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Type</div><div class='profile-description'> type / String</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Glucose</div><div class='profile-description'> mg/dl / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Inhaler Usage</div><div class='profile-description'> times / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Oxygen Saturation</div><div class='profile-description'> percentage / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Peak Expiratory Flow Rate</div><div class='profile-description'> l/min / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Body Temperature</div><div class='profile-description'> celsius / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Pressure Diastolic</div><div class='profile-description'> mmhg / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Blood Pressure Systolic</div><div class='profile-description'> mmhg / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Heart Rate</div><div class='profile-description'> beats/minute / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Respiratory Rate</div><div class='profile-description'> breaths/minute / Integer</div></div>

              <div class='profile-item'><div class='profile-property'>Dietary Calories</div><div class='profile-description'> cal / Integer</div></div>

              
      operationId: write_health_metrics
      summary: Update Health Metrics
      tags:
        - User
      security:
        - oauth:
            - member_write
  /users/me/appointments:
    get:
      description: Get all appointments of current user
      operationId: user appointments
      summary: Get all appointments
      tags:
        - Scheduling
      security:
        - oauth:
            - member_read
  /users/me/test_results:
    get:
      description: Get a list of medical lab’s results from a user’s medical record
      operationId: test_result
      summary: Get Test Results
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/health_graph:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: health_graph
      summary: Get Health Graph
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/adherence_data:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: adherence_data
      summary: Get Adherence Data
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/notifications:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: notifications
      summary: Get Notifications
      tags:
        - Engagement
      security:
        - oauth:
            - member_read
  /users/me/topics_and_goals:
    get:
      description: Get user's topics and goals of interest.
      operationId: topics_and_goals
      summary: Get User Topics/Goals
      tags:
        - Engagement
      security:
        - oauth:
            - member_read
  /users/me:
    get:
      description: Get basic info of current user
      operationId: my_basic_info
      summary: Get User Basic Info
      tags:
        - User
      security:
        - oauth:
            - member_read
  /users/me/register_available:
    post:
      description: Register Availablity
      operationId: register_availability
      summary: Register Availablity
      tags:
        - User
      security:
        - oauth:
            - provider_write
  /users/sign_out:
    get:
      description: User Sign Out
      operationId: user_sign_out
      summary: User Sign Out
      tags:
        - User
      security:
        - {}
  /users/me/availability_info:
    get:
      description: Get Availablity Info
      operationId: get_availability_info
      summary: Get Availablity Info
      tags:
        - User
      security:
        - oauth:
            - provider_read
  /users/me/keep_alive:
    post:
      description: 'Keep Alive Operation: polling every 60 seconds'
      operationId: keep_alive_operation
      summary: Keep Alive Operation
      tags:
        - User
      security:
        - oauth:
            - expert_write
  /users/sign_in:
    post:
      description: User Sign In
      operationId: user_sign_in
      summary: User Sign In
      tags:
        - User
      security:
        - {}
  /users/enterprise_sign_in:
    post:
      description: Enterprise User Sign In
      operationId: enterprise_user_sign_in
      summary: Enterprise User Sign In
      tags:
        - User
      security:
        - {}
  /search?category=questions:
    get:
      description: Search questions
      operationId: search_questions
      summary: Search Questions
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /search?category=tips:
    get:
      description: search tips
      operationId: search_tips
      summary: Search Tips
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /search?category=news:
    get:
      description: search news
      operationId: search_news
      summary: Search News
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /search?category=topics:
    get:
      description: search topics
      operationId: search_topics
      summary: Search Topics
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /search?category=doctor:
    get:
      description: search doctor
      operationId: search_doctor
      summary: Search Experts
      tags:
        - Directory
      security:
        - oauth:
            - member_read
  '/topics/{id}':
    get:
      description: Get topic details by topic ID
      operationId: topics
      summary: Get Topic Details
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /search?category=tags:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: tags
      summary: Get Tags by Query
      tags:
        - Ontology
      security:
        - oauth:
            - member_read
  /search?category=specialties:
    get:
      description: Get specialties by query
      operationId: specialties_by_query
      summary: Get Specialties by Query
      tags:
        - Ontology
      security:
        - oauth:
            - member_read
  '/experts/{id}/referral_graph':
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: referral_graph
      summary: Get Expert Referral Graph
      tags:
        - Directory
  '/experts/{id}/office_hours':
    get:
      description: Get available slots in office hours by expert
      operationId: fetch_office_hours
      summary: Fetch expert office hours
      tags:
        - Scheduling
      security:
        - oauth:
            - member_read
  '/experts/{id}/schedule_appointment':
    post:
      description: Make an virtual appointment according to expert and time slot
      operationId: schedule_appointment
      summary: Schedule virtual appointment
      tags:
        - Scheduling
      security:
        - oauth:
            - member_write
  '/experts/{id}':
    get:
      description: Get expert details
      operationId: expert_details
      summary: Expert Details
      tags:
        - Directory
  '/experts/{id}/known_fors':
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: known_fors
      summary: Get Expert Known Fors
      tags:
        - Directory
  '/experts/{id}/add_to_care_team':
    post:
      description: Add experts to care team
      operationId: add_to_care_team
      summary: Add to Care-Team
      tags:
        - Directory
  '/experts/{id}/remove_from_care_team':
    put:
      description: Remove experts from care team
      operationId: remove_from_care_team
      summary: Remove from Care-Team
      tags:
        - Directory
  /experts/me/chat_sessions_rating:
    get:
      description: Experts see consult rating from patients
      operationId: expert_see_consult_rating
      summary: Expert see consult ratings
      tags:
        - Directory
  experts/me/upcoming_appointments:
    get:
      description: Get expert's upcoming appointments for the following weeks
      operationId: get_upcoming_appointments
      summary: Expert Upcoming Appointments
      tags:
        - Directory
  /experts/me/profile:
    get:
      description: Get current expert's profile
      operationId: Expert Profile
      summary: Get Expert Profile
      tags:
        - Directory
      security:
        - oauth:
            - provider_read
  /experts/me/update_profile:
    post:
      description: |-
        Update profiles for provider. You can update the following fields:
              gender, specialty, medical_school, graduation_year, given_name, family_name, middle_name,
              phone, phone_country_code, address_line_1, address_line_2, address_state, address_city,
              [fellowship_specialty, fellowship_hospital, fellowship_year],
              [residencies_specialty, residencies_primary_hospital, residencies_year],
              specialties
              If you want to customize fields, please contact us.
      operationId: post_update_expert_profile
      summary: Update Expert Profile
      tags:
        - Directory
      security:
        - oauth:
            - provider_write
  /experts/me/feed:
    get:
      description: Get current expert's feed
      operationId: expert_feed
      summary: Get Expert Feed
      tags:
        - Directory
      security:
        - oauth:
            - provider_read
  '/checklists/{id}/mark_complete':
    post:
      description: Mark a checklist as complete
      operationId: Mark checklists
      summary: Mark Action as Complete
      tags:
        - Engagement
      security:
        - oauth:
            - member_write
  '/checklists/{id}/subscribe':
    post:
      description: Subscirbe to a checklist by id
      operationId: subscirbe checklists
      summary: Subscribe to Checklist
      tags:
        - Engagement
      security:
        - oauth:
            - member_write
  /services/prescriptions:
    post:
      description: 'PRIVATE — For access, please contact us.'
      operationId: order_prescription
      summary: Order Prescription
      tags:
        - Services
      security:
        - oauth:
            - member_write
  /services/lab_tests:
    post:
      description: 'PRIVATE — For access, please contact us.'
      operationId: order_lab_tests
      summary: Order Lab Tests
      tags:
        - Services
      security:
        - oauth:
            - member_write
  /payments/transactions:
    post:
      description: 'PRIVATE — For access, please contact us.'
      operationId: create_transaction
      summary: Create Transaction
      tags:
        - Payments
      security:
        - oauth:
            - member_write
  /payments/subscriptions:
    post:
      description: 'PRIVATE — For access, please contact us.'
      operationId: start_subscription
      summary: Start Subscription
      tags:
        - Payments
      security:
        - oauth:
            - member_write
    put:
      description: 'PRIVATE — For access, please contact us.'
      operationId: cancel_subscription
      summary: Cancel Subscription
      tags:
        - Payments
      security:
        - oauth:
            - member_write
  /payments/insurance:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: check_insurance
      summary: Check Insurance Eligibility
      tags:
        - Payments
      security:
        - oauth:
            - member_write
    post:
      description: 'PRIVATE — For access, please contact us.'
      operationId: submit_claim
      summary: Submit Claim
      tags:
        - Payments
      security:
        - oauth:
            - member_write
  /ontology/health_goal:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: health_goal
      summary: Get Health Goal
      tags:
        - Ontology
      security:
        - oauth:
            - member_read
  /ontology/specialties:
    get:
      description: 'PRIVATE — For access, please contact us.'
      operationId: specialties
      summary: Get Specialties
      tags:
        - Ontology
      security:
        - oauth:
            - member_read
  /questions:
    post:
      description: >-
        Ask a question via HealthTap. Doctors will respond quickly and we will
        post answers back to you
      operationId: askQuestion
      summary: Send a Question
      tags:
        - Library
      security:
        - oauth:
            - member_write
  '/questions/{id}':
    get:
      description: Get question details by quesiton ID
      operationId: questions
      summary: Get Question Details
      tags:
        - Library
      security:
        - oauth:
            - member_read
  '/appointments/{id}/cancel':
    put:
      description: Cancel an appointment by id
      operationId: cancel_my_appointment
      summary: Cancel an appointment
      tags:
        - Scheduling
      security:
        - oauth:
            - member_write
  /analytics/concept/co-occurrence:
    get:
      description: >-
        Co-occurrence of Concepts in Population (Demographics, Time Range,
        Geography) API
      operationId: co_occurence_of_concept
      summary: Co-occurrence of concepts
      tags:
        - Analytics
      security:
        - oauth:
            - member_read
  /analytics/concept/frequency:
    get:
      description: >-
        Frequency of Concepts in Population (Demographics, Time Range,
        Geography) API
      operationId: frequency_of_concept
      summary: Frequency of concept
      tags:
        - Analytics
      security:
        - oauth:
            - member_read
  '/news/{id}':
    get:
      description: Get news details by news ID
      operationId: news
      summary: Get News Details
      tags:
        - Library
      security:
        - oauth:
            - member_read
  '/tips/{id}':
    get:
      description: Get tips details by tips ID
      operationId: tips
      summary: Get Tips Details
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /files.json:
    post:
      description: upload a file
      operationId: File
      summary: Upload file
      tags:
        - File
      security:
        - oauth:
            - member_write
  '/chat_sessions/{id}':
    get:
      description: Get chat_session details by chat session id
      operationId: chat_session
      summary: Get Chat Session Details
      tags:
        - ChatSession
      security:
        - oauth:
            - member_read
  '/chat_sessions/{id}/feed':
    get:
      description: Get chat_session feed by chat session id
      operationId: chat_session
      summary: Get Chat Session Feed
      tags:
        - ChatSession
      security:
        - oauth:
            - member_read
  /chat_sessions:
    post:
      description: Start a session
      operationId: start_session
      summary: Start a session
      tags:
        - ChatSession
      security:
        - oauth:
            - member_write
  '/chat_sessions/{id}/rate':
    post:
      description: Rate a consult (chat session)
      operationId: rate_chat_session
      summary: Rate a chat session
      tags:
        - ChatSession
      security:
        - oauth:
            - member_write
            - provider_write
  /speed_tests/configuration:
    get:
      description: Get Speed Test Configuration
      operationId: Get Speed Test
      summary: Get Speed Test Configuration
      tags:
        - Speed Test
      security:
        - oauth:
            - member_read
  /speed_tests:
    post:
      description: Speed Test
      operationId: Create User Speed Report
      summary: Create Speed Test Report
      tags:
        - Speed Test
      security:
        - oauth:
            - member_write
  /speed_tests/download:
    get:
      description: Download Speed Test
      operationId: User Speed Test
      summary: Download Speed Test
      tags:
        - Speed Test
      security:
        - oauth:
            - member_read
  /speed_tests/upload:
    post:
      description: Upload Speed Test
      operationId: User Speed Test
      summary: Upload Speed Test
      tags:
        - Speed Test
      security:
        - oauth:
            - member_write
  /speed_tests/ping:
    get:
      description: Ping Speed Test
      operationId: User Speed Test
      summary: Ping Speed Test
      tags:
        - Speed Test
      security:
        - oauth:
            - member_read
  '/treatment_reviews/{id}':
    get:
      description: Get rateRx details
      operationId: rateRx
      summary: Get Treatment Reviews
      tags:
        - Library
      security:
        - oauth:
            - member_read
  /api/v2.1/logging:
    post:
      description: unified_logging
      operationId: Unified Logging
      summary: Unified Logging
      tags:
        - Logging
      security:
        - oauth: []
  /countries:
    get:
      description: Get all countries details
      operationId: get_countries_details
      summary: Get countries details
      tags:
        - Country
  /api/v2.1/analytics_events:
    post:
      description: Analytics event
      operationId: Analytics Event
      summary: Analytics Event
      tags:
        - Logging
      security:
        - oauth: []
  /notification_settings:
    get:
      description: Fetch all notification settings
      operationId: notification_setting
      summary: Get All Notification Settings
      tags:
        - NotificationSettings
      security:
        - oauth:
            - member_read
  '/notification_settings/:id':
    put:
      description: update notification setting
      operationId: update_notification_setting
      summary: Update Notification Setting
      tags:
        - NotificationSettings
      security:
        - oauth:
            - member_write
  /configurations:
    get:
      description: Fetch configurations
      operationId: configurations
      summary: Get All configurations Settings
      tags:
        - Configurations
      security:
        - oauth:
            - public